# Generated by Django 5.0.1 on 2024-02-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('AD', 'admin'), ('US', 'user')], max_length=50)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_orm.task')),
            ],
        ),
    ]
