# Generated by Django 5.0.1 on 2024-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.ManyToManyField(to='django_orm.task'),
        ),
    ]
